# Generated by Django 3.0.6 on 2020-05-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wybory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
